name: KeithNickel
favicon: null
layout_spectrum: 0.9856914978008717
typography_spectrum: 0.47069638734683394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15420788782648742
  lightness: 0.9250969979912043
  saturation: 0.2966928891837597
  rhythmicContrast: 0.7089375758077949
purpose: []
