name: KeithNickel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94773
title: Unraveling The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090202'
    - '#59391e'
    - '#ba5e3d'
    - '#d97b59'
    - '#ebbf98'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.7089375758077949
purpose: []
